### ISSUE TITLE
dumb-jump-prompt-user-for-choice: Invalid function: helm-build-sync-source

### ISSUE THREAD

**Issue by academikuser** [jacktasia/dumb-jump#153] opened 2017-07-31 09:18 UTC
I am getting the following message 
`dumb-jump-prompt-user-for-choice: Invalid function: helm-build-sync-source`
when trying to jump to a definition with
`dumb-jump-quick-look`    called when my cursor is on myfunction   in  Main.Rmd

Here is my setup:
`pwd    ~/myProject`
`tree`
├── .git
├── Index
│   |-----Main.Rmd
│   |-----.dumbjump

file: ~/myHelperFunctions/R/myfunction.R

`myfunction <- function(arg1){
     setwd("~/myProject")
     return("sucess")
     }`

file:  ~/myProject/Index/.dumbjump
`+/Volumes/HDD/Users/thomas/myHelperFunctions`

file: ~/myProject/Index/Main.Rmd

    ---
    title: "my project"    
    output:
    html_document
    ---

    ## Overview

    ```{r load}
    library("myHelperFunctions")
    myfunction()
    ```

**Comment by academikuser** [comment] 2017-07-31 09:34
Ok, changed three things and now dump-jump is working as expected.
1. move .dumbjump to the same level as .git.

    pwd ~/myProject
    tree
    ├── .git
    ├── .dumbjump
    ├── Index
   │   |-----Main.Rmd

2. trash helm and helm-projectile
`z elpa && trash helm-proj*  helm-20*`

3. restart emacs to reinstall the packages.

**Comment by academikuser** [comment] 2017-07-31 09:47
It also seems to be quite important to have the trailing slash
`    (setq dumb-jump-default-project "/Volumes/HDD/Users/thomas/myHelperFunctions/")`

not

`    (setq dumb-jump-default-project "/Volumes/HDD/Users/thomas/myHelperFunctions")`

**Comment by paynito** [comment] 2017-08-02 09:42
Same thing is happening to me, with quick look and dumb-jump-go.  Any more tricks to debug this?
    
    dumb-jump-prompt-user-for-choice: Invalid function: helm-build-sync-source
    helm-M-x: Invalid function: helm-build-sync-source

**Comment by jacktasia** [comment] 2017-08-02 17:06
@paynito Have you tried re-installing `helm`? It looks like that's what @academikuser ended up  having to do.

**Comment by jacktasia** [comment] 2017-08-15 17:17
I am closing this, but more than happy to re-open if people are still having issues. Just comment here. Thanks

**Closed by jacktasia** 2017-08-15 17:17 UTC

**Comment by nloyola** [comment] 2018-05-04 16:49
I'm running into this issue when I use `dumb-jump-go-prompt` or `dumb-jump-quick-look`. I've done what @academikuser suggested but still no luck.

Here are the package versions I'm using:

* helm-20180503.2215
* helm-projectile-20180418.2223

Any way to fix it?

**Comment by jacktasia** [comment] 2018-05-05 07:04
@nloyola Thanks for the report. Using Emacs 26 might be the issue. It's not out yet so not officially supported. Although this is a good reminder for me to make sure dumb-jump works before it's out. Thanks! 

Let me try loading dumb-jump with helm on Emacs 26 and see if I can figure out what's going on.

**Comment by nloyola** [comment] 2018-05-05 15:40
Thanks for looking into it @jacktasia!

**Comment by jacktasia** [comment] 2018-05-06 21:49
@nloyola I just tried dumb-jump with emacs-26.1-rc1 and it worked as expected.

Please make sure helm is installed correctly:

https://github.com/emacs-helm/helm/wiki#install
https://github.com/emacs-helm/helm/issues/602

If you continue to have issues and you can include a base reproducible example I can try to help more. Hope that helps.

**Comment by nloyola** [comment] 2018-05-07 16:17
@jacktasia thanks for looking into it. Yes, re-installing the package works (note that I'm using `use-package`).
